### ISSUE TITLE
Internal Error when creating portal

### ISSUE THREAD

**Issue by durzanult** [masagameplay/MaSuitePortals#3]
23.11 18:51:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at fi.matiaspaavilainen.masuiteportalsbridge.commands.Set.onCommand(Set.java:64) ~[?:?]
23.11 18:51:19 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/Vector;
23.11 18:51:19 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
23.11 18:51:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-5696c83-b1d149c]
23.11 18:51:19 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'setportal' in plugin MaSuitePortalsBridge v1.1.1

Any Idea what is going on?

**Comment by masagameplay** [comment]
It seems like you are running oudated version of WorldEdit. Also please note that MaSuitePortals only work with 1.13.2 because the Material change. 

I am going to make version for 1.8-.1.12.2 too when I have enough time so you must wait if you are using older version of Minecraft.

**Comment by durzanult** [comment]
> It seems like you are running oudated version of WorldEdit. Also please note that MaSuitePortals only work with 1.13.2 because the Material change.
> 
> I am going to make version for 1.8-.1.12.2 too when I have enough time so you must wait if you are using older version of Minecraft.

...huh? Thats actually far from the truth... I am actually using the latest dev build of worldedit (which might actually be part of the problem). Also, I am using 1.13.2; heck, it even says 1.13.2 several times near the top of the log that I quoted.

**Comment by masagameplay** [comment]
> 
> 
> > It seems like you are running oudated version of WorldEdit. Also please note that MaSuitePortals only work with 1.13.2 because the Material change.
> > I am going to make version for 1.8-.1.12.2 too when I have enough time so you must wait if you are using older version of Minecraft.
> 
> ...huh? Thats actually far from the truth... I am actually using the latest dev build of worldedit (which might actually be part of the problem). Also, I am using 1.13.2; heck, it even says 1.13.2 several times near the top of the log that I quoted.

:oops: Didnt read enough carefully that, sorry :(

There is an error regarding to WorldEdit, seems like the region first position is not set. Do you have Cuboid region (square) or some other shape selected?

**Comment by durzanult** [comment]
At the time I had a cubed region selected. And i did set both positions multiple times and kept getting internal errors. So while one particular instance may have had only one pos set, it doesn't account for all of them.

**Comment by masagameplay** [comment]
Seems like WorldEdit has an update and there were changes in the API. Working version coming soon to SpigotMC forums!

EDIT: Seems like there are lots of changes so there will be delay! Sorry
